roundtrip-option: func(a: option<float32>) -> option<u8>
roundtrip-result: func(a: result<u32, float32>) -> result<float64, u8>

enum e1 { a, b }
roundtrip-enum: func(a: e1) -> e1

variant c1 { a(s32), b(s64) }
variant-c1: func(a: c1) -> c1